final List<String> cities = [
    'All',
    'Riyadh',
    'Jeddah',
    'Makkah',
    'Qatif',
    'Yanbu',
    'Hafr Al-Batin',
    'Taif',
    'Tabuk',
    'Buraydah',
    'Unaizah',
    'Jubail',
    'Jizan',
    'Al Jawf',
    'Hofuf',
    'Gurayat',
    'Dhahran',
    'Bisha',
    'Arar',
    'Abha'
  ];
  
  final List<String> locations = [
    'Riyadh',
    'Jeddah',
    'Makkah',
    'Qatif',
    'Yanbu',
    'Hafr Al-Batin',
    'Taif',
    'Tabuk',
    'Buraydah',
    'Unaizah',
    'Jubail',
    'Jizan',
    'Al Jawf',
    'Hofuf',
    'Gurayat',
    'Dhahran',
    'Bisha',
    'Arar',
    'Abha'
  ];